name = "Chatham / Southeastern Main Line Chislehurst Junction - Shortlands to Swanley & Grove Park to Petts Wood"
display_name = "Chatham / Southeastern Main Line Chislehurst Junction"
description = "A simulation of the the Chislehurst junction where the Southeastern and Chatham Main Lines intersect."
rly_file = "ChathamMainLine-Chislehurst.rly"
ttb_files = [ "ChathamMainLine-Chislehurst OffPeak.ttb", "ChathamMainLine-Chislehurst Peak.ttb",]
ssn_files = []
doc_files = [ "readme-ChathamMainLine-Chislehurst", ]
img_files = [ "ChathamMainLine-Chislehurst.bmp",]
graphic_files = []
country_code = "GB"
year = 2022
factual = true
difficulty = 4
author = "MissCatTrap"
contributors = []
version = "1.0.0"
release_date = "2022-02-10"
